package(default_visibility = ["//visibility:public"])
# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "hello_world_main",
    srcs = ["hello_world_main.cc"],
    deps = ["//demo_lib:hello_great"],
)