package(default_visibility = ["//visibility:public"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cc"],
)

py_binary(
    name = "hello_world_p",
    srcs = ["hello_world_p.py"],
)
