package(default_visibility = ["//visibility:public"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "demo01_talker_",
    srcs = ["demo01_talker_.cc"],
    deps = [
        "//cyber",
        "//cyber/demo_base_proto:student_cc",
        ],
)